/*
 * Stoatworks Labs - About window data for Compander.
 *
 * SEEDED BY HAND on 2026-08-26 for a repo that does not exist in projects.json
 * yet. Every other copy of this file is GENERATED by
 * stoatworks-backend/scripts/sync-about.py from the website's projects.json,
 * which is the one place these facts are written down.
 *
 * ADD compander TO projects.json AND RE-RUN THE SYNC before the first
 * release. Until that happens the guide and page URLs below are 404s: they
 * are the shape the site will use, not links that resolve today.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Compander";
    inline constexpr auto slug = "compander";
    inline constexpr auto hook = "Radio mic companding for video";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "https://stoatworks-labs.com/software/compander/guide/";
    inline constexpr auto page = "https://stoatworks-labs.com/software/compander/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/compander";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
